Repository rlberry-py/rlberry, pull requests merged in 2023-07, with the labels that each got.

#328 Hotfix : Update doc for V0.5.0
  docs/basics/DeepRLTutorial/TutorialDeepRL.rst
  docs/index.rst
  docs/other/using_gym.rst
  docs/thumbnails/example_plot_atari_atlantis_vectorized_ppo.jpg
  docs/thumbnails/example_plot_atari_breakout_vectorized_ppo.jpg
  docs/user_guide.rst
  examples/demo_env/example_atari_atlantis_vectorized_ppo.py
  examples/demo_env/example_atari_breakout_vectorized_ppo.py
  long_tests/torch_agent/ltest_dqn_vs_mdqn_acrobot.py
  rlberry/envs/basewrapper.py
  rlberry/envs/classic_control/acrobot.py
  rlberry/envs/classic_control/mountain_car.py
  rlberry/envs/classic_control/pendulum.py
  rlberry/utils/check_gym_env.py
Labels: documentation

#335 Upgrade from python3.9 to python3.10
  .readthedocs.yml
  README.md
  azure-pipelines.yml
  docs/changelog.rst
  scripts/apptainer_for_tests/README.md
  scripts/apptainer_for_tests/monthly_test_base.sh
  scripts/apptainer_for_tests/rlberry_apptainer__specific_python.def
  scripts/apptainer_for_tests/rlberry_apptainer_base.def
  setup.py
Labels: ready for review

#349 issue #188
  rlberry/agents/adaptiveql/adaptiveql.py
  rlberry/agents/agent.py
  rlberry/agents/torch/dqn/dqn.py
  rlberry/agents/torch/ppo/ppo.py
  rlberry/agents/torch/reinforce/reinforce.py
  rlberry/envs/bandits/bandit_base.py
Labels: ready for review

#348 Reverse order of lower and upper bounds arguments in bounded UCB/MOSS indices
  examples/demo_bandits/plot_TS_bandit.py
  rlberry/agents/bandits/indices.py
Labels: enhancement, ready for review

#345 rename Bernoulli UCB to Bounded UCB
  examples/demo_bandits/plot_TS_bandit.py
Labels: documentation, ready for review

#326 Add Soft Actor-Critic (SAC)
  docs/api.rst
  docs/changelog.rst
  examples/demo_agents/demo_SAC.py
  rlberry/agents/experimental/tests/test_sac.py
  rlberry/agents/experimental/torch/__init__.py
  rlberry/agents/experimental/torch/sac/improvements.txt
  rlberry/agents/experimental/torch/sac/sac.py
  rlberry/agents/experimental/torch/sac/utils.py
  rlberry/agents/torch/__init__.py
  rlberry/agents/torch/a2c/a2c.py
  rlberry/agents/torch/sac/__init__.py
  rlberry/agents/torch/sac/sac.py
  rlberry/agents/torch/sac/sac_utils.py
  rlberry/agents/torch/tests/test_sac.py
  rlberry/agents/torch/utils/models.py
  rlberry/tests/test_agent_extra.py
  rlberry/utils/check_agent.py
Labels: ready for review, Marathon

#357 New Contributors
  README.md
  docs/changelog.rst
  docs/contributors.rst
  scripts/fetch_contributors.py
Labels: documentation, ready for review
